<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Vetrsion="10.0.9" />
    <!-- other shared packages go here too -->
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageVersion Include="NetCord.Hosting" Version="1.0.0-beta.12" />
    <PackageVersion Include="NetCord.Hosting.Services" Version="1.0.0-beta.12" />
    <PackageVersion Include="NetCordAddons.Services" Version="1.1.9" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="8.0.28" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageVersion Include="xunit" Version="2.4.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.4.5" />
    <PackageVersion Include="coverlet.collector" Version="6.0.0" />
  </ItemGroup>
</Project>