services:
  postgres:
    image: postgres:17
    container_name: ian-postgres
    environment:
      POSTGRES_USER: ian
      POSTGRES_PASSWORD: goodboy
      POSTGRES_DB: ian
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes: 
  postgres-data:

